# Generated by Django 3.0.5 on 2021-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_taxi', models.CharField(choices=[('Libre', 'Libre'), ('Ocupado', 'Ocupado')], default='Libre', max_length=250)),
                ('conductor', models.CharField(blank=None, max_length=250, unique=True)),
                ('matricula', models.CharField(blank=None, max_length=250, unique=True)),
                ('ubicacion_actual', models.CharField(blank=None, max_length=250)),
                ('destino', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
