# Generated by Django 3.2.8 on 2021-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_taxis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='coord_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='coord_ubicacion_actual',
            field=models.FloatField(blank=None, default=0),
            preserve_default=False,
        ),
    ]
