# Generated by Django 3.2.8 on 2021-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_taxis', '0002_auto_20211112_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='coord_destino',
            field=models.FloatField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='taxi',
            name='coord_ubicacion_actual',
            field=models.FloatField(blank=None, null=True),
        ),
    ]
