# Generated by Django 3.0.5 on 2021-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
