# Generated by Django 3.2.8 on 2021-11-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitar', '0002_auto_20211110_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
